name: Deploy to AWS
on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AKIAQUFLQMHI2CAUIVX6 }}
          aws-secret-access-key: ${{ secrets.xUxxwxgu9CmpfB6jkeKwk2wD37sHAJf0Kp5R7lAS }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Deploy using AWS CLI
        run: |
          aws s3 ls                      # Example AWS command
          aws s3 sync . s3://sas-github-workflow --delete
